// Suggestions for the breed box on the patient step. The vet can type anything; these just
// keep spelling consistent, which helps similar-case matching (backend compares breeds by name).
import type { Species } from "./types";

// Only cats and dogs have a list; other species just get OTHER_BREEDS (see breedsFor).
export const BREEDS: Partial<Record<Species, readonly string[]>> = {
  cat: [
    "Domestic Shorthair",
    "Domestic Mediumhair",
    "Domestic Longhair",
    "Abyssinian",
    "American Shorthair",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Cornish Rex",
    "Devon Rex",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Himalayan",
    "Maine Coon",
    "Manx",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Siamese",
    "Siberian",
    "Sphynx",
    "Tonkinese",
    "Turkish Angora",
  ],
  dog: [
    "Labrador Retriever",
    "Golden Retriever",
    "German Shepherd",
    "French Bulldog",
    "English Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "Dachshund",
    "German Shorthaired Pointer",
    "Pembroke Welsh Corgi",
    "Australian Shepherd",
    "Yorkshire Terrier",
    "Boxer",
    "Cavalier King Charles Spaniel",
    "Doberman Pinscher",
    "Great Dane",
    "Miniature Schnauzer",
    "Siberian Husky",
    "Bernese Mountain Dog",
    "Shih Tzu",
    "Boston Terrier",
    "Pomeranian",
    "Havanese",
    "Shetland Sheepdog",
    "Cocker Spaniel",
    "Border Collie",
    "Chihuahua",
    "Pug",
    "Maltese",
    "Pit Bull Terrier",
    "Goldendoodle",
    "Labradoodle",
  ],
};

/** Also offered for every species. */
export const OTHER_BREEDS = ["Mixed breed", "Unknown"] as const;

/** Breed suggestions for a species (just OTHER_BREEDS when it has no list). */
export const breedsFor = (species: Species): readonly string[] => [...(BREEDS[species] ?? []), ...OTHER_BREEDS];
