import type { Plan } from "./types";

// Mochi/Alex demo from the project plan. Mirrors what POST /api/plans builds from the
// "vomiting-senior-cat" template (backend/app/data), so /plan/demo works with no backend.
// Full estimate $780; essentials $360 (the only items ticked to start, as in real plans); Alex's
// budget $400. Prices are samples.

export const DEMO_PLAN_ID = "demo";

export const samplePlan: Plan = {
  id: DEMO_PLAN_ID,
  pet: { name: "Mochi", species: "cat", age_years: 12, breed: "Domestic Shorthair", weight_lbs: 9.5, reason: "Vomiting for 2 days" },
  owner_name: "Alex",
  budget: 400,
  payment_choice: "pay_today",
  status: "draft",
  share_token: null,
  symptoms: ["vomiting", "not-eating"],
  notes: null,
  owner_email: null,
  source: "template",
  suggested: [],
  items: [
    {
      id: "demo-exam",
      catalog_id: "exam",
      name: "Sick-visit exam",
      price: 75,
      group: "essential",
      selected: true,
      explanation: {
        what: "The vet checks your pet from nose to tail.",
        why: "Tells the vet how sick your pet is and what to check next.",
        if_postponed: "Needed for any treatment today.",
        steps: "The vet looks at the eyes, ears, mouth and skin, listens to the heart and lungs, feels the belly and joints, and takes temperature and weight. It takes about 15–20 minutes, and you can stay with your pet.",
        cost_includes: "The vet's time for the hands-on exam and talking through what they found. Tests and treatments are listed separately.",
        questions: ["What are you most worried about after the exam?", "Which tests would change what we do today?", "What signs at home mean I should call you?"],
      },
    },
    {
      id: "demo-antiemetic-inj",
      catalog_id: "antiemetic-inj",
      name: "Anti-nausea injection",
      price: 55,
      group: "essential",
      selected: true,
      explanation: {
        what: "A shot that stops nausea and vomiting for about 24 hours.",
        why: "Helps your pet keep food and water down and feel better fast.",
        if_postponed: "Vomiting may continue and dehydration can get worse.",
        steps: "A small injection under the skin, usually at the back of the neck. It takes a few seconds and starts working within about an hour.",
        cost_includes: "The medicine and giving the injection.",
        questions: ["When can I offer food and water again?", "What should I do if vomiting starts again tonight?", "Will my pet need anti-nausea pills at home?"],
      },
    },
    {
      id: "demo-sq-fluids",
      catalog_id: "sq-fluids",
      name: "Fluids under the skin",
      price: 60,
      group: "essential",
      selected: true,
      explanation: {
        what: "Fluids given under the skin to rehydrate.",
        why: "Vomiting pets lose water quickly, especially older cats.",
        if_postponed: "Dehydration can make your pet weaker and harder to treat.",
        steps: "A small needle goes under the loose skin between the shoulders and fluid flows in for a few minutes. It leaves a soft bump that is absorbed over several hours.",
        cost_includes: "The sterile fluids, the needle and line, and the technician's time.",
        questions: ["How will I know if my pet is still dehydrated?", "Could we give fluids at home if this helps?", "When should my pet start drinking normally again?"],
      },
    },
    {
      id: "demo-blood-panel",
      catalog_id: "blood-panel",
      name: "Blood panel",
      price: 170,
      group: "essential",
      selected: true,
      explanation: {
        what: "Blood tests that check organs like the kidneys and liver, plus blood cells.",
        why: "Finds common causes of vomiting in older cats, like kidney disease.",
        if_postponed: "The vet may miss an underlying problem that changes treatment.",
        steps: "A small blood sample is taken from a leg or the neck, which takes a couple of minutes. Many results come back the same day; some take 1–2 days from the lab.",
        cost_includes: "Drawing the blood, the lab tests for organ function and blood cell counts, and the vet reviewing the results with you.",
        questions: ["When will the results be back, and how will you tell me?", "Which results would change today's treatment?", "Will we need to repeat this later?"],
      },
    },
    {
      id: "demo-xrays-abd",
      catalog_id: "xrays-abd",
      name: "Belly X-rays",
      price: 250,
      group: "soon",
      selected: false,
      explanation: {
        what: "Pictures of the belly.",
        why: "Looks for blockages or swallowed objects.",
        if_postponed: "Often fine to do at a recheck if vomiting improves. Come back sooner if it gets worse.",
        steps: "Your pet lies on a padded table while 2–3 pictures of the belly are taken. It takes about 10–15 minutes and doesn't hurt. Some pets need a little sedation to lie still.",
        cost_includes: "Taking the pictures (usually two views) and the vet reading them. Sedation, if needed, is separate.",
        questions: ["What are you looking for on these X-rays?", "If they look normal, what's the next step?", "Would a specialist also read them?"],
      },
    },
    {
      id: "demo-urinalysis",
      catalog_id: "urinalysis",
      name: "Urine test",
      price: 70,
      group: "soon",
      selected: false,
      explanation: {
        what: "A test of a urine sample.",
        why: "Adds detail to the blood panel on kidney health.",
        if_postponed: "Usually fine at a recheck within 1–2 weeks.",
        steps: "The vet collects a small urine sample, often with a thin needle straight from the bladder, which is quick and cleaner than a catch at home. Results usually take less than a day.",
        cost_includes: "Collecting the sample and testing it for concentration, sugar, protein, blood, crystals and signs of infection.",
        questions: ["Should I bring a sample from home instead?", "Would a urine culture be needed too?", "What do the results tell us that the blood panel doesn't?"],
      },
    },
    {
      id: "demo-t4",
      catalog_id: "t4",
      name: "Thyroid test",
      price: 65,
      group: "optional",
      selected: false,
      explanation: {
        what: "Measures thyroid hormone.",
        why: "An overactive thyroid is common in older cats and can cause vomiting.",
        if_postponed: "Usually fine to check at the next visit.",
        steps: "A thyroid level is measured from a blood sample, often from the same draw as the blood panel, so there's no extra needle. Results usually take 1–2 days.",
        cost_includes: "The lab test and the vet reviewing the result.",
        questions: ["If the thyroid is high, what are the treatment options?", "Can this be run from today's blood sample?", "How often should it be rechecked?"],
      },
    },
    {
      id: "demo-rx-diet",
      catalog_id: "rx-diet",
      name: "Prescription diet (1 bag)",
      price: 35,
      group: "optional",
      selected: false,
      explanation: {
        what: "A gentle food that is easy on the stomach.",
        why: "Can help the stomach settle for a few days.",
        if_postponed: "Your vet can suggest a bland diet at home instead.",
        steps: "You take home a bag of a gentle, easy-to-digest food. Mix it in with the usual food over a few days, or feed it on its own if your vet says so.",
        cost_includes: "One bag of prescription food.",
        questions: ["How long should my pet eat this food?", "Can I make a bland diet at home instead?", "What if my pet won't eat it?"],
      },
    },
  ],
};
